identifier: lcn0t6cbdfy7ebpe
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: muehler-website
homeFolder: E:\OneDrive\Documents\MuehlerWebsite\muehler-website
distFolder: dist/muehler-website
outDir: E:\OneDrive\Documents\MuehlerWebsite\muehler-website\dist\static
handle404: ''
allowErrorCollect: true
